=== solvire/php-json-schema-generator/tests/data/example-address2.schema.json
{
    "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
    "type": "object",
    "required": [
        "address",
        "bar",
        "phoneNumber",
        "test"
    ],
    "properties": {
        "address": {
            "type": "object",
            "required": [
                "city",
                "streetAddress"
            ],
            "properties": {
                "streetAddress": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                }
            }
        },
        "bar": {
            "type": "object",
            "required": [
                "barAddress",
                "city"
            ],
            "properties": {
                "barAddress": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                }
            }
        },
        "phoneNumber": {
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "type": "object",
                        "required": [
                            "number",
                            "type"
                        ],
                        "properties": {
                            "type": {
                                "type": "string"
                            },
                            "number": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "type": "object",
                        "required": [
                            "digits",
                            "number",
                            "type"
                        ],
                        "properties": {
                            "type": {
                                "type": "string"
                            },
                            "number": {
                                "type": "string"
                            },
                            "digits": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    }
                ]
            }
        },
        "test": {
            "type": "string"
        }
    }
}

=== solvire/php-json-schema-generator/tests/data/example-address2.input.json
{
	"address":{
		"streetAddress": "21 2nd Street",
		"city":"New York"
	},
	"bar":{
		"barAddress": "123 Fake st",
 		"city":"Los Angeles"
	},
	"phoneNumber":
	[
		{
			"type":"home",
 			"number":"212 555-1234"
		},
		{
			"type":"work",
			"number":"805 666-1234",
			"digits":"818-666-1234"
		},
		{
			"type":"cell",
			"number":"919 777-1234"
		},
        ["block_below"]
	],
	"test" : "string"
}
